### ISSUE TITLE
Requests are not in unicode although documentation says so

### ISSUE THREAD

**Issue by jespertk** [issuu/broen#1]
The encoding of HTTP headers is ISO-8859-1. No mapping to unicode takes place.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by doktoren** [comment]
Why was this issue closed? It hasn't been fixed.

**Comment by haljin** [comment]
#5 s about to go live

**Comment by doktoren** [comment]
I already looked at that pull request but:
A) It is not yet merged.
B) Digging into the changes it states that it is simply a refactoring. Switching from ISO-8859-1 to unicode is not backwards compatible (I assume it has been switched because the documentation still says unicode).
```
## Migrating to 2.0
The only difference in 2.0 is that `broen` no longer uses Yaws, switching instead to `cowboy`. That means `yaws` configuration is no longer relevant.
```
